meta_profuct_name: "TennisMate"
meta_title: "TennisMate - Find your next hitting partner"
meta_description: "The best app for finding a tennis partner with a skill level that matches yours"
meta_image: "meta_image.jpg"
